version: "3.9"
services:
  server:
    image: roofinder-api
    build: ./server
    restart: always
    ports:
    - 5000:5000
    volumes:
      - ./server:/server
    environment:
      - FLASK_ENV=production
  web:
    image: roofinder
    build: ./client
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on:
      - server