FROM python:3.8

WORKDIR /server

ENV FLASK_APP = server.py

ENV FLASK_ENV = production

COPY ./requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install opencv-python-headless==4.5.3.56

COPY . .

EXPOSE 5000
CMD [ "python","server.py" ]