FROM python:3

WORKDIR /server

ENV FLASK_APP = server.py

ENV FLASK_ENV = production

COPY ./requirements.txt .

RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 5000
CMD [ "gunicorn","-b","0.0.0.0:5000","server:app" ]